// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Elasticsearch ODBC Installer Custom Actions")]
[assembly: AssemblyDescriptionAttribute("MSI installer custom actions for the Elasticsearch ODBC driver.")]
[assembly: GuidAttribute("4498d74b-e5c5-48bb-a9d4-8cc55b7b0909")]
[assembly: AssemblyProductAttribute("Elasticsearch ODBC Installer Custom Actions")]
[assembly: AssemblyCompanyAttribute("Elasticsearch B.V.")]
[assembly: AssemblyCopyrightAttribute("Elastic License. Copyright Elasticsearch.")]
[assembly: AssemblyTrademarkAttribute("Elasticsearch is a trademark of Elasticsearch B.V.")]
[assembly: AssemblyVersionAttribute("0.0.0")]
[assembly: AssemblyFileVersionAttribute("0.0.0")]
[assembly: AssemblyInformationalVersionAttribute("0.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Elasticsearch ODBC Installer Custom Actions";
        internal const System.String AssemblyDescription = "MSI installer custom actions for the Elasticsearch ODBC driver.";
        internal const System.String Guid = "4498d74b-e5c5-48bb-a9d4-8cc55b7b0909";
        internal const System.String AssemblyProduct = "Elasticsearch ODBC Installer Custom Actions";
        internal const System.String AssemblyCompany = "Elasticsearch B.V.";
        internal const System.String AssemblyCopyright = "Elastic License. Copyright Elasticsearch.";
        internal const System.String AssemblyTrademark = "Elasticsearch is a trademark of Elasticsearch B.V.";
        internal const System.String AssemblyVersion = "0.0.0";
        internal const System.String AssemblyFileVersion = "0.0.0";
        internal const System.String AssemblyInformationalVersion = "0.0.0";
    }
}
