// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Elasticsearch DSN Editor Launcher")]
[assembly: AssemblyDescriptionAttribute("Elasticsearch DSN Editor Launcher.")]
[assembly: GuidAttribute("71bebff7-652e-4b26-9ec3-caef947d368c")]
[assembly: AssemblyProductAttribute("Elasticsearch DSN Editor Launcher")]
[assembly: AssemblyCompanyAttribute("Elasticsearch B.V.")]
[assembly: AssemblyCopyrightAttribute("Elastic License. Copyright Elasticsearch.")]
[assembly: AssemblyTrademarkAttribute("Elasticsearch is a trademark of Elasticsearch B.V.")]
[assembly: AssemblyVersionAttribute("0.0.0")]
[assembly: AssemblyFileVersionAttribute("0.0.0")]
[assembly: AssemblyInformationalVersionAttribute("0.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Elasticsearch DSN Editor Launcher";
        internal const System.String AssemblyDescription = "Elasticsearch DSN Editor Launcher.";
        internal const System.String Guid = "71bebff7-652e-4b26-9ec3-caef947d368c";
        internal const System.String AssemblyProduct = "Elasticsearch DSN Editor Launcher";
        internal const System.String AssemblyCompany = "Elasticsearch B.V.";
        internal const System.String AssemblyCopyright = "Elastic License. Copyright Elasticsearch.";
        internal const System.String AssemblyTrademark = "Elasticsearch is a trademark of Elasticsearch B.V.";
        internal const System.String AssemblyVersion = "0.0.0";
        internal const System.String AssemblyFileVersion = "0.0.0";
        internal const System.String AssemblyInformationalVersion = "0.0.0";
    }
}
