// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Installer")]
[assembly: AssemblyDescriptionAttribute("Elasticsearch ODBC Installer.")]
[assembly: GuidAttribute("44555887-c439-470c-944d-8866ec3d7067")]
[assembly: AssemblyProductAttribute("Elasticsearch ODBC Installer")]
[assembly: AssemblyMetadataAttribute("GitBuildHash","35639d")]
[assembly: AssemblyCompanyAttribute("Elasticsearch B.V.")]
[assembly: AssemblyCopyrightAttribute("Elastic License. Copyright Elasticsearch.")]
[assembly: AssemblyTrademarkAttribute("Elasticsearch is a trademark of Elasticsearch B.V.")]
[assembly: AssemblyVersionAttribute("6.5.0")]
[assembly: AssemblyFileVersionAttribute("6.5.0")]
[assembly: AssemblyInformationalVersionAttribute("6.5.0-windows-x86_64")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Installer";
        internal const System.String AssemblyDescription = "Elasticsearch ODBC Installer.";
        internal const System.String Guid = "44555887-c439-470c-944d-8866ec3d7067";
        internal const System.String AssemblyProduct = "Elasticsearch ODBC Installer";
        internal const System.String AssemblyMetadata_GitBuildHash = "35639d";
        internal const System.String AssemblyCompany = "Elasticsearch B.V.";
        internal const System.String AssemblyCopyright = "Elastic License. Copyright Elasticsearch.";
        internal const System.String AssemblyTrademark = "Elasticsearch is a trademark of Elasticsearch B.V.";
        internal const System.String AssemblyVersion = "6.5.0";
        internal const System.String AssemblyFileVersion = "6.5.0";
        internal const System.String AssemblyInformationalVersion = "6.5.0-windows-x86_64";
    }
}
