// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Elasticsearch ODBC Installer")]
[assembly: AssemblyDescriptionAttribute("MSI installer for the Elasticsearch ODBC driver.")]
[assembly: GuidAttribute("44555887-c439-470c-944d-8866ec3d7067")]
[assembly: AssemblyProductAttribute("Elasticsearch ODBC Installer")]
[assembly: AssemblyCompanyAttribute("Elasticsearch B.V.")]
[assembly: AssemblyCopyrightAttribute("Elastic License. Copyright Elasticsearch.")]
[assembly: AssemblyTrademarkAttribute("Elasticsearch is a trademark of Elasticsearch B.V.")]
[assembly: AssemblyVersionAttribute("7.0.0")]
[assembly: AssemblyFileVersionAttribute("7.0.0")]
[assembly: AssemblyInformationalVersionAttribute("7.0.0-windows-x86_64-341e86")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Elasticsearch ODBC Installer";
        internal const System.String AssemblyDescription = "MSI installer for the Elasticsearch ODBC driver.";
        internal const System.String Guid = "44555887-c439-470c-944d-8866ec3d7067";
        internal const System.String AssemblyProduct = "Elasticsearch ODBC Installer";
        internal const System.String AssemblyCompany = "Elasticsearch B.V.";
        internal const System.String AssemblyCopyright = "Elastic License. Copyright Elasticsearch.";
        internal const System.String AssemblyTrademark = "Elasticsearch is a trademark of Elasticsearch B.V.";
        internal const System.String AssemblyVersion = "7.0.0";
        internal const System.String AssemblyFileVersion = "7.0.0";
        internal const System.String AssemblyInformationalVersion = "7.0.0-windows-x86_64-341e86";
    }
}
